// Export utilities for generating PDFs and downloadable content

export const exportResumeAnalysis = (analysis: any) => {
  const content = `
SKILLBRIDGE AI PRO - RESUME ANALYSIS REPORT
Generated: ${new Date().toLocaleDateString()}

RESUME SCORE: ${analysis.score}/100

ATS COMPATIBILITY: ${analysis.atsAnalysis?.passRate || 0}%

SKILLS IDENTIFIED:
${analysis.skills?.map((s: any) => `- ${s.name} (${s.importance})`).join('\n') || 'None'}

IMPROVEMENT SUGGESTIONS:
${analysis.suggestions?.map((s: any) => `[${s.type.toUpperCase()}] ${s.title}\n${s.description}`).join('\n\n') || 'None'}

ATS ISSUES:
${analysis.atsAnalysis?.issues?.map((i: string) => `- ${i}`).join('\n') || 'None'}

---
Generated by SkillBridge AI Pro - Microsoft Imagine Cup 2025
  `.trim();

  downloadAsFile(content, `resume-analysis-${Date.now()}.txt`, 'text/plain');
};

export const exportRoadmap = (roadmap: any) => {
  const content = `
SKILLBRIDGE AI PRO - CAREER ROADMAP
Generated: ${new Date().toLocaleDateString()}

90-DAY LEARNING ROADMAP

${roadmap.milestones?.map((m: any, i: number) => `
MILESTONE ${i + 1}: ${m.title}
Status: ${m.status}
Duration: ${m.duration}
Description: ${m.description}

Tasks:
${m.tasks?.map((t: string) => `- ${t}`).join('\n') || 'None'}
`).join('\n') || 'No milestones'}

---
Generated by SkillBridge AI Pro - Microsoft Imagine Cup 2025
  `.trim();

  downloadAsFile(content, `career-roadmap-${Date.now()}.txt`, 'text/plain');
};

export const exportSkillGap = (analysis: any) => {
  const content = `
SKILLBRIDGE AI PRO - SKILL GAP ANALYSIS
Generated: ${new Date().toLocaleDateString()}

TARGET ROLE: ${analysis.role}
MATCH PERCENTAGE: ${analysis.matchPercentage}%

MATCHING SKILLS:
${analysis.matchingSkills?.map((s: any) => 
  `- ${s.name} (Priority: ${s.priority}, Level: ${s.currentLevel}/${s.requiredLevel})`
).join('\n') || 'None'}

MISSING SKILLS:
${analysis.missingSkills?.map((s: any) => 
  `- ${s.name} (Priority: ${s.priority}, Time to Learn: ${s.timeToLearn}, Required Level: ${s.requiredLevel})`
).join('\n') || 'None'}

---
Generated by SkillBridge AI Pro - Microsoft Imagine Cup 2025
  `.trim();

  downloadAsFile(content, `skill-gap-analysis-${Date.now()}.txt`, 'text/plain');
};

function downloadAsFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

